services:
  scrum-app:
    image: node:latest
    command: "npm install"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: accounts
  mysql:
    image: mysql:8.0
    volumes:
      - accounts-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: accounts
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:3000
    environment:
      - PMA_ARBITRARY=1
  nginx:
    image: nginx
    volumes:
     - ./templates:/etc/nginx/templates
    ports:
     - "8080:80"
    environment:
     - NGINX_HOST=foobar.com
     - NGINX_PORT=80
  
volumes:
  accounts-mysql-data: